environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - choco install make -y
  - 'set PATH=%PYTHON%\\Scripts;%PATH%'
  - make install

build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%LOCALAPPDATA%\pypoetry\cache'
  - '%PROGRAMDATA%\chocolatey\bin'
  - '%PROGRAMDATA%\chocolatey\lib'

test_script:
  - make test

on_success:
  - poetry run codecov -f coverage.xml
